/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osgi.demo.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osgi.demo.model.OSGi_Foo;
import com.liferay.osgi.demo.service.OSGi_FooLocalServiceUtil;

/**
 * The extended model base implementation for the OSGi_Foo service. Represents a row in the &quot;OSGi_Foo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OSGi_FooImpl}.
 * </p>
 *
 * @author milen
 * @see OSGi_FooImpl
 * @see com.liferay.osgi.demo.model.OSGi_Foo
 * @generated
 */
@ProviderType
public abstract class OSGi_FooBaseImpl extends OSGi_FooModelImpl
	implements OSGi_Foo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o s gi_ foo model instance should use the {@link OSGi_Foo} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			OSGi_FooLocalServiceUtil.addOSGi_Foo(this);
		}
		else {
			OSGi_FooLocalServiceUtil.updateOSGi_Foo(this);
		}
	}
}